name: Issue Change Push

on:
  issues:
    types: [opened, edited, closed]

jobs:
  auto_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Modify file
        run: |
          echo "Issue event at $(date)" >> issue-log.txt

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto update from issue change"
          git push
